function populateform()
{				
	var amountform;
	var rechForm=document.mobilerecharge;
	var moboperator=rechForm.Operator.value;
	
	 if(moboperator=="AIRTEL" || moboperator=="TATASKY" || moboperator=="VIDEOCONDTH"){
     
	 amountform="<table border=\"0\" width=\"100%\"><tr valign=\"top\" ><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"> Amount&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"><input type=\"text\" name=\"amount\" value=\"\" class=\"bala\" size=\"5\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"5\" style=\"width:150px;\"/></td></tr><tr valign=\"top\" style=\"padding-bottom:20px\"><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">DTH&nbsp;Account&nbsp;Number&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\"><input type=\"text\" name=\"mobileNo\" id=\"mobileNo\" class=\"bala\" size=\"20\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"10\" style=\"width:150px;\" /></td></tr></table>";
 	
	  }
	 if(moboperator=="SUNDIRECTTV"){
     amountform="<table border=\"0\" width=\"100%\"><tr valign=\"top\" ><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"> Amount&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"><select name='amount' id='amount' class='from_text' style='width: 150px;'><option value='00'>Select Amount</option><option value='25'>25</option><option value='100'>100</option><option value='133'>133</option> <option value='143'>143</option><option value='200'>200</option><option value='300'>300</option><option value='405'>405</option><option value='500'>500</option><option value='790'>790</option><option value='1000'>1000</option></select></td></tr><tr valign=\"top\" style=\"padding-bottom:20px\"><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">DTH&nbsp;Account&nbsp;Number&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\"><input type=\"text\" name=\"mobileNo\" id=\"mobileNo\" class=\"bala\" size=\"20\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"11\" style=\"width:150px;\" /></td></tr></table>";
 	
	  }
	 if(moboperator=="RelianceBTV"){
     
	 amountform="<table border=\"0\" width=\"100%\"><tr valign=\"top\" ><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"> Amount&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"><input type=\"text\" name=\"amount\" value=\"\" class=\"bala\" size=\"5\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"5\" style=\"width:150px;\"/></td></tr><tr valign=\"top\" style=\"padding-bottom:20px\"><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">DTH&nbsp;Account&nbsp;Number&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\"><input type=\"text\" name=\"mobileNo\" id=\"mobileNo\" class=\"bala\" size=\"20\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"13\" style=\"width:150px;\" /></td></tr></table>";
	  }

if(moboperator=="DISH"){
     
	 amountform="<table border=\"0\" width=\"100%\"><tr valign=\"top\" ><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"> Amount&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"><input type=\"text\" name=\"amount\" value=\"\" class=\"bala\" size=\"5\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"5\" style=\"width:150px;\"/></td></tr><tr valign=\"top\" style=\"padding-bottom:20px\"><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">DTH&nbsp;Account&nbsp;Number&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\"><input type=\"text\" name=\"mobileNo\" id=\"mobileNo\" class=\"bala\" size=\"20\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"11\" style=\"width:150px;\" /></td></tr></table>";
	  }
	  }

	   if(moboperator=="-1"){
     amountform="<table border=\"0\" width=\"100%\"><tr valign=\"top\" ><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"> Amount&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\" style=\"padding-bottom:15px\"><select name='amount' id='amount' class='from_text' style='width: 150px;'><option value='00'>Select Amount</option><option value='50'>50</option><option value='100'>100</option><option value='200'>200</option> <option value='300'>300</option><option value='333'>333</option><option value='444'>444</option><option value='500'>500</option><option value='1000'>1000</option></select></td></tr><tr valign=\"top\" style=\"padding-bottom:20px\"><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">Mobile&nbsp;Number&nbsp;&nbsp;<font size=\"1\" color=\"red\" onmouseover=\"alertmessage()\">&nbsp;&nbsp;*</font></td><td width=\"2%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\">&nbsp;&nbsp;:&nbsp;&nbsp;</td><td width=\"40%\" align=\"right\" valign=\"middle\" class=\"Trebuchet_b\"><input type=\"text\" name=\"mobileNo\" id=\"mobileNo\" class=\"bala\" size=\"20\"   onKeyPress=\"return digitonly(this,event)\" onKeyDown=\"chk_keys();\" maxlength=\"10\" style=\"width:150px;\" /></td></tr></table>";
 	
	  }

	document.getElementById("amountform").innerHTML=amountform;	

}