
var currency = new Array("ALL","DZD","ANG","ARS","AWG","AUD","BSD","BHD","BBD","BYR","BZD","BMD","BTN","BOB","BWP","BRL","GBP","BND","BGN","BIF","XPF","CAD","KYD","CLP","CNY","COP","KMF","CRC","HRK","CUP","CYP","CZK","DKK","DOP","XCD","EGP","SVC","EEK","ETB","EUR","FJD","GMD","GHC","GTQ","GNF","HTG","HNL","HKD","HUF","ISK","INR","IDR","IRR","IQD","ILS","JMD","JPY","JOD","KZT","KES","KWD","LVL","LBP","LSL","LTL","MOP","MKD","MGA","MWK","MYR","MVR","MTL","MRO","MUR","MXN","MDL","MNT","MAD","NAD","NPR","NZD","NIO","NGN","NOK","OMR","PKR","PAB","PGK","PYG","PEN","PHP","PLN","QAR","RUB","RWF","WST","STD","SAR","SCR","SLL","SGD","SKK","SIT","SBD","ZAR","KRW","LKR","SDD","SZL","SEK","CHF","TWD","BDT","TZS","THB","TOP","TTD","TND","TRY","USD","UGX","UAH","UYU","AED","VUV","VEB","VND","YER","ZMK","ZWD");
var country = new Array("","DZ","AN","AR","AW","AU","BS","BH","BB","BY","BZ","BM","BT","BO","BW","BR","GB","BN","BG","BI","XP","CA","KY","CL","CN","CO","KM","CR","HR","CU","CY","CZ","DK","DO","XC","EG","SV","EE","ET","EU","FJ","GM","GH","GT","GN","HT","HN","HK","HU","IS","IN","ID","IR","IQ","IL","JM","JP","JO","KZ","KE","KW","LV","LB","LS","LT","MO","MK","MG","MW","MY","MV","MT","MR","MU","MX","MD","MN","MA","NA","NP","NZ","NI","NG","NO","OM","PK","PA","PG","PY","PE","PH","PL","QA","RU","RW","WS","ST","SA","SC","SL","SG","SK","SI","SB","ZA","KR","LK","SD","SZ","SE","CH","TW","BD","TZ","TH","TO","TT","TN","TR","US","UG","UA","UY","AE","VU","VE","VN","YE","ZM","ZW");
var rate = new Array("81.967","65.616","1.7799","3.1565","1.7905","1.0787","0.9975","0.3768","1.9948","2144","1.9696","1.001","45.745","7.5301","0.2197","1.6829","0.4955","1.4501","1.2745","1139","78.064","0.989","0.82","442.28","7.1123","1888.5","323.72","517.86","4.7438","1","0.3978","16.302","4.8473","33.875","2.6874","5.4734","8.7489","10.175","9.0909","0.6503","1.4947","20.999","9267.8","7.6628","4370.6","36.153","18.889","7.7881","172.71","67.658","40.453","9115.7","9345.7","1211","3.5945","70.372","102.07","0.7082","128.35","64.599","0.2714","0.4518","1507.6","8.045","2.2406","8","41.963","1759.9","139.54","3.2","12.799","0.2934","247.03","26.997","10.833","10.8","1174.3","7.4404","8","65.231","1.2629","18.031","118.49","5.1519","0.3849","62.539","1","3.0193","4690.4","2.8653","41.135","2.3201","3.635","23.866","545.25","2.3843","14480","3.7495","8.0192","2990.4","1.3877","21.088","164.69","6.9979","8.0321","949.66","107.74","234.41","8.045","6.1124","1.0208","30.674","68.352","1163.4","31.535","1.8439","6.25","1.181","1.2485","1","1707.9","5.0454","24.348","3.671","94.966","2147.3","15915","198.09","3738.3","30003");

var fromFlag = new Array(119,16,5,39,100,56); var nVal = 1;
var toFlag   = new Array(39,16,56,50,5,100);
document.write('<form name="calcForm"><table width="220" border="0" cellpadding="0" cellspacing="0"><tr><td width="65" align="right" valign="middle" colspan="1" style="font-family:Verdana, sans-serif; font-size:11px; font-weight:bold; color:#000000">Amount:&#160;</td><td width="155" align="left" valign="middle" colspan="1"><input type="text" name="inV" value="1" onChange="javascript:Cvalue();" size="20" maxlength="50" style="font-family:Arial, sans-serif; font-size:12px; font-weight:normal; color:#000000"></td></tr><tr><td height="11"></td></tr><tr><td width="65" align="right" valign="middle" colspan="1" style="font-family:Verdana, sans-serif; font-size:11px; font-weight:bold; color:#000000">From:&#160;</td><td width="155" align="left" valign="middle" colspan="1"><SELECT NAME="from" onChange="Cvalue(); changeFlag();" style="font-family:Arial, sans-serif; font-size:12px; font-weight:normal; color:#000000"><OPTION VALUE="0"></OPTION><OPTION VALUE="1">Algerian Dinar</OPTION><OPTION VALUE="2">Antilles Guilder</OPTION><OPTION VALUE="3">Argentine Peso</OPTION><OPTION VALUE="4">Aruba Guilder</OPTION><OPTION VALUE="5">Australian Dollar</OPTION><OPTION VALUE="6">Bahamanian Dollar</OPTION><OPTION VALUE="7">Bahraini Dinar</OPTION><OPTION VALUE="8">Barbados Dollar</OPTION><OPTION VALUE="9">Belarus Ruble</OPTION><OPTION VALUE="10">Belize Dollar</OPTION><OPTION VALUE="11">Bermuda Dollar</OPTION><OPTION VALUE="12">Bhutan Ngultrum</OPTION><OPTION VALUE="13">Bolivian Boliviano</OPTION><OPTION VALUE="14">Botswana Pula</OPTION>'
 + '	<OPTION VALUE="15">Brazilian Real</OPTION>'
 + '	<OPTION VALUE="16">British Pound</OPTION>'
 + '	<OPTION VALUE="17">Brunei Dollar</OPTION>'
 + '	<OPTION VALUE="18">Bulgarian Lev</OPTION>'
 + '	<OPTION VALUE="19">Burundi Franc</OPTION>'
 + '	<OPTION VALUE="20">CFP Franc</OPTION>'
 + '	<OPTION VALUE="21">Canadian Dollar</OPTION>'
 + '	<OPTION VALUE="22">Cayman Dollar</OPTION>'
 + '	<OPTION VALUE="23">Chilean Peso</OPTION>'
 + '	<OPTION VALUE="24">Chinese Yuan</OPTION>'
 + '	<OPTION VALUE="25">Colombian Peso</OPTION>'
 + '	<OPTION VALUE="26">Comoros Franc</OPTION>'
 + '	<OPTION VALUE="27">Costa Rican Colon</OPTION>'
 + '	<OPTION VALUE="28">Croatian Kuna</OPTION>'
 + '	<OPTION VALUE="29">Cuban Peso</OPTION>'
 + '	<OPTION VALUE="30">Cyprus Pound</OPTION>'
 + '	<OPTION VALUE="31">Czech Koruna</OPTION>'
 + '	<OPTION VALUE="32">Danish Krone</OPTION>'
 + '	<OPTION VALUE="33">Dominican R. Peso</OPTION>'
 + '	<OPTION VALUE="34">East Caribbean Dollar</OPTION>'
 + '	<OPTION VALUE="35">Egyptian Pound</OPTION>'
 + '	<OPTION VALUE="36">El Salvador Dollar</OPTION>'
 + '	<OPTION VALUE="37">Estonian Kroon</OPTION>'
 + '	<OPTION VALUE="38">Ethiopian Birr</OPTION>'
 + '	<OPTION VALUE="39">Euro</OPTION>'
 + '	<OPTION VALUE="40">Fiji Dollar</OPTION>'
 + '	<OPTION VALUE="41">Gambia Dalasi</OPTION>'
 + '	<OPTION VALUE="42">Ghanaian Cedi</OPTION>'
 + '	<OPTION VALUE="43">Guatemalan Quetzal</OPTION>'
 + '	<OPTION VALUE="44">Guinea Franc</OPTION>'
 + '	<OPTION VALUE="45">Haitian Gourde</OPTION>'
 + '	<OPTION VALUE="46">Honduran Lempira</OPTION>'
 + '	<OPTION VALUE="47">Hong Kong Dollar</OPTION>'
 + '	<OPTION VALUE="48">Hungarian Forint</OPTION>'
 + '	<OPTION VALUE="49">Iceland Krona</OPTION>'
 + '	<OPTION VALUE="50">Indian Rupee</OPTION>'
 + '	<OPTION VALUE="51">Indonesian Rupiah</OPTION>'
 + '	<OPTION VALUE="52">Iranian Rial</OPTION>'
 + '	<OPTION VALUE="53">Iraqi Dinar</OPTION>'
 + '	<OPTION VALUE="54">Israeli New Sheqel</OPTION>'
 + '	<OPTION VALUE="55">Jamaican Dollar</OPTION>'
 + '	<OPTION VALUE="56">Japanese Yen</OPTION>'
 + '	<OPTION VALUE="57">Jordanian Dinar</OPTION>'
 + '	<OPTION VALUE="58">Kazakhstan Tenge</OPTION>'
 + '	<OPTION VALUE="59">Kenyan Shilling</OPTION>'
 + '	<OPTION VALUE="60">Kuwaiti Dinar</OPTION>'
 + '	<OPTION VALUE="61">Latvian Lat</OPTION>'
 + '	<OPTION VALUE="62">Lebanese Pound</OPTION>'
 + '	<OPTION VALUE="63">Lesotho Maloti</OPTION>'
 + '	<OPTION VALUE="64">Lithuanian Litas</OPTION>'
 + '	<OPTION VALUE="65">Macao Patacas</OPTION>'
 + '	<OPTION VALUE="66">Macedonian Denar</OPTION>'
 + '	<OPTION VALUE="67">Madagascar Ariary</OPTION>'
 + '	<OPTION VALUE="68">Malawi Kwacha</OPTION>'
 + '	<OPTION VALUE="69">Malaysian Ringgit</OPTION>'
 + '	<OPTION VALUE="70">Maldive Rufiyaa</OPTION>'
 + '	<OPTION VALUE="71">Maltese Lira</OPTION>'
 + '	<OPTION VALUE="72">Mauritanian Ouguiya</OPTION>'
 + '	<OPTION VALUE="73">Mauritian Rupee</OPTION>'
 + '	<OPTION VALUE="74">Mexican Peso</OPTION>'
 + '	<OPTION VALUE="75">Moldova Leu</OPTION>'
 + '	<OPTION VALUE="76">Mongolian Tugrik</OPTION>'
 + '	<OPTION VALUE="77">Moroccan Dirham</OPTION>'
 + '	<OPTION VALUE="78">Namibia Dollar</OPTION>'
 + '	<OPTION VALUE="79">Nepalese Rupee</OPTION>'
 + '	<OPTION VALUE="80">New Zealand Dollar</OPTION>'
 + '	<OPTION VALUE="81">Nicaraguan Cordoba Oro</OPTION>'
 + '	<OPTION VALUE="82">Nigerian Naira</OPTION>'
 + '	<OPTION VALUE="83">Norwegian Kroner</OPTION>'
 + '	<OPTION VALUE="84">Omani Rial</OPTION>'
 + '	<OPTION VALUE="85">Pakistan Rupee</OPTION>'
 + '	<OPTION VALUE="86">Panamanian Balboa</OPTION>'
 + '	<OPTION VALUE="87">Papua New Guinea Kina</OPTION>'
 + '	<OPTION VALUE="88">Paraguay Guarani</OPTION>'
 + '	<OPTION VALUE="89">Peruvian Nuevo Sol</OPTION>'
 + '	<OPTION VALUE="90">Philippine Peso</OPTION>'
 + '	<OPTION VALUE="91">Polish Zloty</OPTION>'
 + '	<OPTION VALUE="92">Qatari Rial</OPTION>'
 + '	<OPTION VALUE="93">Russian Ruble</OPTION>'
 + '	<OPTION VALUE="94">Rwandan Franc</OPTION>'
 + '	<OPTION VALUE="95">Samoa Tala</OPTION>'
 + '	<OPTION VALUE="96">Sao Tome/Principe Dobra</OPTION>'
 + '	<OPTION VALUE="97">Saudi Riyal</OPTION>'
 + '	<OPTION VALUE="98">Seychelles Rupee</OPTION>'
 + '	<OPTION VALUE="99">Sierra Leone Leone</OPTION>'
 + '	<OPTION VALUE="100">Singapore Dollar</OPTION>'
 + '	<OPTION VALUE="101">Slovak Koruna</OPTION>'
 + '	<OPTION VALUE="102">Slovenian Tolar</OPTION>'
 + '	<OPTION VALUE="103">Solomon Dollar</OPTION>'
 + '	<OPTION VALUE="104">South African Rand</OPTION>'
 + '	<OPTION VALUE="105">South Korean Won</OPTION>'
 + '	<OPTION VALUE="106">Sri Lanka Rupee</OPTION>'
 + '	<OPTION VALUE="107">Sudanese Dinar</OPTION>'
 + '	<OPTION VALUE="108">Swaziland Emalangeni</OPTION>'
 + '	<OPTION VALUE="109">Swedish Krona</OPTION>'
 + '	<OPTION VALUE="110">Swiss Franc</OPTION>'
 + '	<OPTION VALUE="111">Taiwan Dollar</OPTION>'
 + '	<OPTION VALUE="112">Taka</OPTION>'
 + '	<OPTION VALUE="113">Tanzania Shiling</OPTION>'
 + '	<OPTION VALUE="114">Thai Baht</OPTION>'
 + '	<OPTION VALUE="115">Tonga Pa\'anga</OPTION>'
 + '	<OPTION VALUE="116">Trinidad Dollar</OPTION>'
 + '	<OPTION VALUE="117">Tunisia Dinar</OPTION>'
 + '	<OPTION VALUE="118">Turkish Lira (New)</OPTION>'
 + '	<OPTION VALUE="119">US Dollar</OPTION>'
 + '	<OPTION VALUE="120">Uganda Shilling</OPTION>'
 + '	<OPTION VALUE="121">Ukrainian Hryvnia</OPTION>'
 + '	<OPTION VALUE="122">Uruguayan Peso</OPTION>'
 + '	<OPTION VALUE="123">Utd. Arab Emir. Dirham</OPTION>'
 + '	<OPTION VALUE="124">Vanuatu Vatu</OPTION>'
 + '	<OPTION VALUE="125">Venezuelan Bolivar</OPTION>'
 + '	<OPTION VALUE="126">Vietnamese Dong</OPTION>'
 + '	<OPTION VALUE="127">Yemen Rial</OPTION>'
 + '	<OPTION VALUE="128">Zambia Kwacha</OPTION>'
 + '	<OPTION VALUE="129">Zimbabwe Dollar</OPTION>'
 + '</SELECT>'
 + '</td>'
 + '</tr>'
 + '<tr>'
 + '<td height="11"></td>'
 + '</tr>'
 + '<td width="65" align="right" valign="middle" colspan="1" style="font-family:Verdana, sans-serif; font-size:11px; font-weight:bold; color:#000000">To:&#160;</td>'
 + '<td width="155" align="left" valign="middle" colspan="1">'
 + '<SELECT NAME="to" onChange="Cvalue(); changeFlag(\'to\');" style="font-family:Arial, sans-serif; font-size:12px; font-weight:normal; color:#000000">'
 + '	<OPTION VALUE="0"></OPTION>'
 + '	<OPTION VALUE="1">Algerian Dinar</OPTION>'
 + '	<OPTION VALUE="2">Antilles Guilder</OPTION>'
 + '	<OPTION VALUE="3">Argentine Peso</OPTION>'
 + '	<OPTION VALUE="4">Aruba Guilder</OPTION>'
 + '	<OPTION VALUE="5">Australian Dollar</OPTION>'
 + '	<OPTION VALUE="6">Bahamanian Dollar</OPTION>'
 + '	<OPTION VALUE="7">Bahraini Dinar</OPTION>'
 + '	<OPTION VALUE="8">Barbados Dollar</OPTION>'
 + '	<OPTION VALUE="9">Belarus Ruble</OPTION>'
 + '	<OPTION VALUE="10">Belize Dollar</OPTION>'
 + '	<OPTION VALUE="11">Bermuda Dollar</OPTION>'
 + '	<OPTION VALUE="12">Bhutan Ngultrum</OPTION>'
 + '	<OPTION VALUE="13">Bolivian Boliviano</OPTION>'
 + '	<OPTION VALUE="14">Botswana Pula</OPTION>'
 + '	<OPTION VALUE="15">Brazilian Real</OPTION>'
 + '	<OPTION VALUE="16">British Pound</OPTION>'
 + '	<OPTION VALUE="17">Brunei Dollar</OPTION>'
 + '	<OPTION VALUE="18">Bulgarian Lev</OPTION>'
 + '	<OPTION VALUE="19">Burundi Franc</OPTION>'
 + '	<OPTION VALUE="20">CFP Franc</OPTION>'
 + '	<OPTION VALUE="21">Canadian Dollar</OPTION>'
 + '	<OPTION VALUE="22">Cayman Dollar</OPTION>'
 + '	<OPTION VALUE="23">Chilean Peso</OPTION>'
 + '	<OPTION VALUE="24">Chinese Yuan</OPTION>'
 + '	<OPTION VALUE="25">Colombian Peso</OPTION>'
 + '	<OPTION VALUE="26">Comoros Franc</OPTION>'
 + '	<OPTION VALUE="27">Costa Rican Colon</OPTION>'
 + '	<OPTION VALUE="28">Croatian Kuna</OPTION>'
 + '	<OPTION VALUE="29">Cuban Peso</OPTION>'
 + '	<OPTION VALUE="30">Cyprus Pound</OPTION>'
 + '	<OPTION VALUE="31">Czech Koruna</OPTION>'
 + '	<OPTION VALUE="32">Danish Krone</OPTION>'
 + '	<OPTION VALUE="33">Dominican R. Peso</OPTION>'
 + '	<OPTION VALUE="34">East Caribbean Dollar</OPTION>'
 + '	<OPTION VALUE="35">Egyptian Pound</OPTION>'
 + '	<OPTION VALUE="36">El Salvador Dollar</OPTION>'
 + '	<OPTION VALUE="37">Estonian Kroon</OPTION>'
 + '	<OPTION VALUE="38">Ethiopian Birr</OPTION>'
 + '	<OPTION VALUE="39">Euro</OPTION>'
 + '	<OPTION VALUE="40">Fiji Dollar</OPTION>'
 + '	<OPTION VALUE="41">Gambia Dalasi</OPTION>'
 + '	<OPTION VALUE="42">Ghanaian Cedi</OPTION>'
 + '	<OPTION VALUE="43">Guatemalan Quetzal</OPTION>'
 + '	<OPTION VALUE="44">Guinea Franc</OPTION>'
 + '	<OPTION VALUE="45">Haitian Gourde</OPTION>'
 + '	<OPTION VALUE="46">Honduran Lempira</OPTION>'
 + '	<OPTION VALUE="47">Hong Kong Dollar</OPTION>'
 + '	<OPTION VALUE="48">Hungarian Forint</OPTION>'
 + '	<OPTION VALUE="49">Iceland Krona</OPTION>'
 + '	<OPTION VALUE="50">Indian Rupee</OPTION>'
 + '	<OPTION VALUE="51">Indonesian Rupiah</OPTION>'
 + '	<OPTION VALUE="52">Iranian Rial</OPTION>'
 + '	<OPTION VALUE="53">Iraqi Dinar</OPTION>'
 + '	<OPTION VALUE="54">Israeli New Sheqel</OPTION>'
 + '	<OPTION VALUE="55">Jamaican Dollar</OPTION>'
 + '	<OPTION VALUE="56">Japanese Yen</OPTION>'
 + '	<OPTION VALUE="57">Jordanian Dinar</OPTION>'
 + '	<OPTION VALUE="58">Kazakhstan Tenge</OPTION>'
 + '	<OPTION VALUE="59">Kenyan Shilling</OPTION>'
 + '	<OPTION VALUE="60">Kuwaiti Dinar</OPTION>'
 + '	<OPTION VALUE="61">Latvian Lat</OPTION>'
 + '	<OPTION VALUE="62">Lebanese Pound</OPTION>'
 + '	<OPTION VALUE="63">Lesotho Maloti</OPTION>'
 + '	<OPTION VALUE="64">Lithuanian Litas</OPTION>'
 + '	<OPTION VALUE="65">Macao Patacas</OPTION>'
 + '	<OPTION VALUE="66">Macedonian Denar</OPTION>'
 + '	<OPTION VALUE="67">Madagascar Ariary</OPTION>'
 + '	<OPTION VALUE="68">Malawi Kwacha</OPTION>'
 + '	<OPTION VALUE="69">Malaysian Ringgit</OPTION>'
 + '	<OPTION VALUE="70">Maldive Rufiyaa</OPTION>'
 + '	<OPTION VALUE="71">Maltese Lira</OPTION>'
 + '	<OPTION VALUE="72">Mauritanian Ouguiya</OPTION>'
 + '	<OPTION VALUE="73">Mauritian Rupee</OPTION>'
 + '	<OPTION VALUE="74">Mexican Peso</OPTION>'
 + '	<OPTION VALUE="75">Moldova Leu</OPTION>'
 + '	<OPTION VALUE="76">Mongolian Tugrik</OPTION>'
 + '	<OPTION VALUE="77">Moroccan Dirham</OPTION>'
 + '	<OPTION VALUE="78">Namibia Dollar</OPTION>'
 + '	<OPTION VALUE="79">Nepalese Rupee</OPTION>'
 + '	<OPTION VALUE="80">New Zealand Dollar</OPTION>'
 + '	<OPTION VALUE="81">Nicaraguan Cordoba Oro</OPTION>'
 + '	<OPTION VALUE="82">Nigerian Naira</OPTION>'
 + '	<OPTION VALUE="83">Norwegian Kroner</OPTION>'
 + '	<OPTION VALUE="84">Omani Rial</OPTION>'
 + '	<OPTION VALUE="85">Pakistan Rupee</OPTION>'
 + '	<OPTION VALUE="86">Panamanian Balboa</OPTION>'
 + '	<OPTION VALUE="87">Papua New Guinea Kina</OPTION>'
 + '	<OPTION VALUE="88">Paraguay Guarani</OPTION>'
 + '	<OPTION VALUE="89">Peruvian Nuevo Sol</OPTION>'
 + '	<OPTION VALUE="90">Philippine Peso</OPTION>'
 + '	<OPTION VALUE="91">Polish Zloty</OPTION>'
 + '	<OPTION VALUE="92">Qatari Rial</OPTION>'
 + '	<OPTION VALUE="93">Russian Ruble</OPTION>'
 + '	<OPTION VALUE="94">Rwandan Franc</OPTION>'
 + '	<OPTION VALUE="95">Samoa Tala</OPTION>'
 + '	<OPTION VALUE="96">Sao Tome/Principe Dobra</OPTION>'
 + '	<OPTION VALUE="97">Saudi Riyal</OPTION>'
 + '	<OPTION VALUE="98">Seychelles Rupee</OPTION>'
 + '	<OPTION VALUE="99">Sierra Leone Leone</OPTION>'
 + '	<OPTION VALUE="100">Singapore Dollar</OPTION>'
 + '	<OPTION VALUE="101">Slovak Koruna</OPTION>'
 + '	<OPTION VALUE="102">Slovenian Tolar</OPTION>'
 + '	<OPTION VALUE="103">Solomon Dollar</OPTION>'
 + '	<OPTION VALUE="104">South African Rand</OPTION>'
 + '	<OPTION VALUE="105">South Korean Won</OPTION>'
 + '	<OPTION VALUE="106">Sri Lanka Rupee</OPTION>'
 + '	<OPTION VALUE="107">Sudanese Dinar</OPTION>'
 + '	<OPTION VALUE="108">Swaziland Emalangeni</OPTION>'
 + '	<OPTION VALUE="109">Swedish Krona</OPTION>'
 + '	<OPTION VALUE="110">Swiss Franc</OPTION>'
 + '	<OPTION VALUE="111">Taiwan Dollar</OPTION>'
 + '	<OPTION VALUE="112">Taka</OPTION>'
 + '	<OPTION VALUE="113">Tanzania Shiling</OPTION>'
 + '	<OPTION VALUE="114">Thai Baht</OPTION>'
 + '	<OPTION VALUE="115">Tonga Pa\'anga</OPTION>'
 + '	<OPTION VALUE="116">Trinidad Dollar</OPTION>'
 + '	<OPTION VALUE="117">Tunisia Dinar</OPTION>'
 + '	<OPTION VALUE="118">Turkish Lira (New)</OPTION>'
 + '	<OPTION VALUE="119">US Dollar</OPTION>'
 + '	<OPTION VALUE="120">Uganda Shilling</OPTION>'
 + '	<OPTION VALUE="121">Ukrainian Hryvnia</OPTION>'
 + '	<OPTION VALUE="122">Uruguayan Peso</OPTION>'
 + '	<OPTION VALUE="123">Utd. Arab Emir. Dirham</OPTION>'
 + '	<OPTION VALUE="124">Vanuatu Vatu</OPTION>'
 + '	<OPTION VALUE="125">Venezuelan Bolivar</OPTION>'
 + '	<OPTION VALUE="126">Vietnamese Dong</OPTION>'
 + '	<OPTION VALUE="127">Yemen Rial</OPTION>'
 + '	<OPTION VALUE="128">Zambia Kwacha</OPTION>'
 + '	<OPTION VALUE="129">Zimbabwe Dollar</OPTION>'
 + '</SELECT>'
 + '</td>'
 + '</tr>'
 + '<tr>'
 + '<td height="11"></td>'
 + '</tr>'
 + '<tr>'
 + '<td width="65" align="right" valign="middle" colspan="1"></td>'
 + '<td width="155" align="left" valign="middle" colspan="1"></td>'
 + '</tr>'
 + '<tr>'
 + '<td height="11"></td>'
 + '</tr>'
 + '<tr>'
 + '<td width="65" align="right" valign="middle" colspan="1" style="font-family:Verdana, sans-serif; font-size:11px; font-weight:bold; color:#000000">Result:&#160;</td>'
 + '<td width="155" align="left" valign="middle" colspan="1"><input type="Text" name="outV" value="" onFocus="blur()" size="20" maxlength="50" style="font-family:Arial, sans-serif; font-size:12px; font-weight:normal; color:#000000"></td>'
 + '</tr>'
 + '<tr>'
 + '<td width="220" height="35" align="center" valign="bottom" colspan="2" class="provab"></td>'
 + '</tr>'
 + '</table></form>');

