name: Build Proxima

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:

  build_proxima:
    name: Build Proxima
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'
      - run: jar -cvf admin.war admin >/dev/null
      - run: jar -cvf agent.war agent >/dev/null
      - run: jar -cvf collection.war collection >/dev/null
      - run: jar -cvf DS.war DS >/dev/null
      - run: jar -cvf DSMRA.war DSMRA >/dev/null
      - run: jar -cvf MDS.war MDS >/dev/null
      - run: jar -cvf MRA1.0.war MRA1.0 >/dev/null
      - run: jar -cvf ROOT.war ROOT >/dev/null
      - run: jar -cvf schedular.war schedular >/dev/null
      - run: ls -alh
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          version: latest
      - name: Available platforms
        run: echo ${{ steps.buildx.outputs.platforms }}
      - name: Login to Github Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: arpitjindal97
          password: ${{ secrets.GIT_PAT_TOKEN }}
      - name: Build Image
        run: docker build -t ghcr.io/msmartpay/proxima:latest . -f Dockerfile
      - name: Push Image
        run: docker push ghcr.io/msmartpay/proxima:latest
